# SPDX-License-Identifier: GPL-2.0
#
userprogs-always-y += task_isol_userloop task_isol_computation task_isol_oneshot
task_isol_userloop-objs := task_isol.o task_isol_userloop.o
task_isol_computation-objs := task_isol.o task_isol_computation.o
task_isol_oneshot-objs := task_isol.o task_isol_oneshot.o

userccflags += -I usr/include


#$(CC) $^ -o $@
